# Generated by Django 4.2.6 on 2023-10-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_dob_alter_userprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(),
        ),
    ]
